### ISSUE TITLE
blake2 strongsums not consistent for RELEASE build.

### ISSUE THREAD

**Issue by dbaarda** [librsync/librsync#103]
This is probably a gcc -O3 bug, not a librsync bug, but I thought I'd better mention it here because it's potentially very nasty.

Using ccmake to set the CMAKE_BUILD_TYPE to RELEASE and running "make check" on a Debian system using gcc version (Debian 6.3.0-11) 6.3.0 20170321, the sumset_test fails with an exception. Running the sumset_test binary repeatedly randomly ends with one of two different errors;

sumset_test: /home/abo/src/librsync/librsync/tests/sumset_test.c:99: main: Assertion `memcmp(&strong, "\x39\xa7\xeb\x9f\xed\xc1", 6) == 0' failed.

or;

sumset_test: /home/abo/src/librsync/librsync/tests/sumset_test.c:129: main: Assertion `rs_signature_find_match(&sig, weak, &buf[15*16], 16) == 15*16' failed.

Note that the assertion on line 99 is checking that the blake2 strongsum has a particular value. For it to occasionally get past this test to fail at line 129 means that sometimes it gives the expected sum, and sometimes it doesn't. Giving different strong sums for the same data will break librsync's block matching in potentially data-corrupting ways.

Note that with CMAKE_BUILD_TYPE set to DEBUG, the tests pass as expected. Using clang instead of gcc the tests pass as expected. This makes me suspect that this is actually a gcc -O3 bug, though it is also possible that blake2 is using some borderline undefined behavior code.

**Comment by dbaarda** [comment]
Although this appears to be a very scary blake2 bug for RELEASE builds using gcc, in practice many other tests (such as the comparison between old, md4, and new versions done in #97) seem to show that it works correctly in practice. It's highly likely that this problem is actually non-deterministic gcc -O3 behavior for the assert statements used by the tests.

**Comment by amoghe** [comment]
Any chance this is due to https://lists.debian.org/debian-devel/2017/06/msg00308.html ?

**Comment by dbaarda** [comment]
Unlikely. I'm running on the following CPU;

Intel(R) Atom(TM) CPU D525   @ 1.80GHz

I don't believe that fits the "Skylake" and "Kaby Lake" that bug is referring to.

**Comment by deajan** [comment]
Trying to play with librsync 2.0.2 in order to gain some speed in a backup program.
Is it safe to use CFLAGS=-O3 or should I stick with non release cmake ?
Thanks.

**Comment by dbaarda** [comment]
I believe this problem was fixed in #113 which included an updated blake2 implementation. This fix has been included since release v2.0.1, so CFLAGS=-O3 should be fine. All the tests now pass correctly with a release build.

Note setting CMAKE_BUILD_TYPE=RELEASE by running 'ccmake .' sets C_FLAGS="-O3 -DNDEBUG" for you.

**Comment by deajan** [comment]
Thanks for the clarification :)
