### ISSUE TITLE
Signature of a file without IO and file descriprors

### ISSUE THREAD

**Issue by mntw** [librsync/librsync#110]
Is there any way to generate signature to memory without writing in on a disk? Now i always have to wirte it on a disk with public API.

```
rs_result rs_sig_file(FILE *old_file, FILE *sig_file,
                      size_t block_len, size_t strong_len,
              rs_magic_number sig_magic,
              rs_stats_t *stats);
```

**Comment by dbaarda** [comment]
You can use the lower level pull (callback driven) or streaming (pushing buffers) API's instead, documented here;

https://github.com/librsync/librsync/blob/master/doc/pull.md
https://github.com/librsync/librsync/blob/master/doc/streaming.md

These can take and generate data however you like.

I'm going to mark this fixed.

**Comment by mntw** [comment]
Ok, thank you. Is there any examples? Or maybe some projects that uses this approach?

**Comment by dbaarda** [comment]
The whole file API is implemented using the pull API in whole.c here;

https://github.com/librsync/librsync/blob/fb0e0ad2d5ba29c9e74993b958c7838109c7462f/src/whole.c#L90

Using callbacks for reading/writing files defined in buf.c here;

https://github.com/librsync/librsync/blob/fb0e0ad2d5ba29c9e74993b958c7838109c7462f/src/buf.c#L88

And the pull API is implemented using the streaming API in  job.c here;

https://github.com/librsync/librsync/blob/fb0e0ad2d5ba29c9e74993b958c7838109c7462f/src/job.c#L191
