### ISSUE TITLE
rdiff is unusably slow when creating deltas for disk images

### ISSUE THREAD

**Issue by eomanis** [librsync/librsync#118]
I have an x86_64 system for everyday use that runs Arch Linux off a 240 GB SATA SSD.

Every few months I get a guilty conscience as to my lack of a reasonable data backup strategy and decide to back up this SSD completely to an offline storage. To this end, I power the system down, attach an additional 1.5 TB conventional hard disk and a USB thumb drive containing a portable Linux OS, and boot said portable OS. Then I proceed to dump the system's 240 GB SSD's contents into a binary file on the 1.5 TB disk.
By now, the target directory looks like this:
```
[root@mysystem raw]# ls -l
-rw------- 1 root root 240054280192 10. Jul 2016  sda.sysbackup.raw.2016-07-10.bin
-rw------- 1 root root 240054280192  1. Sep 2016  sda.sysbackup.raw.2016-08-30.bin
-rw------- 1 root root 240054280192 29. Jan 2017  sda.sysbackup.raw.2017-01-29.bin
-rw------- 1 root root 240054280192 26. Apr 01:42 sda.sysbackup.raw.2017-04-26.bin
-rw------- 1 root root 240054280192 26. Sep 16:18 sda.sysbackup.raw.2017-09-26.bin
```
Now these days the 240 GB SSD is feeling a bit tight and I am considering upgrading to larger SSD. With that thought came the insight that I would likely run into space problems with these full-disk backups, should I for example aim for a 1 TB SSD. I looked around for a binary data deduplication tool for single large files, and guess what I found :-)

So I familiarized myself with rdiff, and I decided deduplicate the disk image files in what I would here call a "reverse" direction, meaning that the newest image should always be there as a full image, and the next-older one as a delta file to that one, and the even-next-older as a delta to said next-older image, and so on.
The directory might look like this then (The delta file sizes are of course made up):
```
[root@mysystem raw]# ls -l
-rw------- 1 root root   4336985575 10. Jul 2016  sda.sysbackup.raw.2016-07-10.bin.delta
-rw------- 1 root root  18377865911  1. Sep 2016  sda.sysbackup.raw.2016-08-30.bin.delta
-rw------- 1 root root  12963278584 29. Jan 2017  sda.sysbackup.raw.2017-01-29.bin.delta
-rw------- 1 root root   7696672554 26. Apr 01:42 sda.sysbackup.raw.2017-04-26.bin.delta
-rw------- 1 root root 240054280192 26. Sep 16:18 sda.sysbackup.raw.2017-09-26.bin
```
To recover an older image, I would chain as many `rdiff -- patch` calls as required to reach the desired backup, like so, here to restore the second image from the top (2016-08-30) to a disk "/dev/sdc":
```
[root@mysystem raw]# cat sda.sysbackup.raw.2017-09-26.bin \
  | rdiff -- patch - sda.sysbackup.raw.2017-04-26.bin.delta - \
  | rdiff -- patch - sda.sysbackup.raw.2017-01-29.bin.delta - \
  | rdiff -- patch - sda.sysbackup.raw.2016-08-30.bin.delta - \
  | dd iflag=fullblock bs=8M of=/dev/sdc oflag=direct status=progress
```
Straightforward stuff.

For starters I wanted to convert the existing full images into delta images, and I would of course start out by converting the oldest full image 2016-07-10 into a delta image based on the next-newer full image, 2016-08-30, working successively upwards to the more recent images.

So I created a signature file of 2016-08-30:
```
[root@mysystem raw]# rdiff -- signature \
  sda.sysbackup.raw.2016-08-30.bin \
  /home/myuser/tmp/sda.sysbackup.raw.2016-08-30.bin.signature
```
That yielded a 4.2 GB signature file in reasonable time, and clearly reading the base file fast enough was the bottleneck here; my 4-core system had a continuous load of 20% on all cores, smooth going as it should be.

Next step, creating the actual delta file. To prevent I/O contention I decided to write it to a Samba network drive, from which I know it can easily gobble up upwards of 100 MB per second (Gigabit Ethernet):
```
[root@mysystem raw]# rdiff -- delta \
  /home/myuser/tmp/sda.sysbackup.raw.2016-08-30.bin.signature \
  sda.sysbackup.raw.2016-07-10.bin \
  /media/networkdrive/backup/sda.sysbackup.raw.2016-07-10.bin.delta
```
Then I waited and did other stuff. Now and then I had a look at the delta file to see it grow. It grew all right, however, it was growing far more slowly than I expected it to. Surely the images could not be _that_ similar? And even if they were, I assumed identical sections would be processed very quickly, leading to a somewhat continuous delta file growth.
I looked at the system load and noticed that rdiff was non-stop flooring one of the 4 available processor cores, which indicated a processing bottleneck, as opposed to the data-reading bottleneck when creating the signature file.

After more than 2 hours the delta file had grown to a measly 220 MB.
At that point I came to the conclusion that the delta file would not be completed in any sort of reasonable time and SIGTERMed rdiff.

Here is what rdiff says about itself:
```
[root@mysystem raw]# rdiff -V
rdiff (librsync 1.0.0) [x86_64-unknown-linux-gnu]
Copyright (C) 1997-2014 by Martin Pool, Andrew Tridgell and others.
http://librsync.sourcefrog.net/
Capabilities: 64 bit files

librsync comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of librsync under the terms of the GNU
Lesser General Public License.  For more information about these
matters, see the files named COPYING.
```
```
[root@mysystem raw]# rdiff --help
Usage: rdiff [OPTIONS] signature [BASIS [SIGNATURE]]
             [OPTIONS] delta SIGNATURE [NEWFILE [DELTA]]
             [OPTIONS] patch BASIS [DELTA [NEWFILE]]

Options:
  -v, --verbose             Trace internal processing
  -V, --version             Show program version
  -?, --help                Show this help message
  -s, --statistics          Show performance statistics
Signature generation options:
  -H, --hash=ALG            Hash algorithm: blake2 (default), md4
Delta-encoding options:
  -b, --block-size=BYTES    Signature block size
  -S, --sum-size=BYTES      Set signature strength
      --paranoia            Verify all rolling checksums
IO options:
  -I, --input-size=BYTES    Input buffer size
  -O, --output-size=BYTES   Output buffer size
  -z, --gzip[=LEVEL]        gzip-compress deltas
  -i, --bzip2[=LEVEL]       bzip2-compress deltas
```

**Comment by dbaarda** [comment]
Things to be aware of;

1) If the images are compressed, they are unlikely to have any matching blocks. Compression does that. There is a workaround; using gzip --rsyncable, which sacrifices a little bit of compression for a result that can still be rsync'ed or rdiff'ed efficiently. It might be worth doing that anyway to save some space.

2) rdiff v1.0.0 is kinda old. There have been some significant performance improvements to librsync since then. We are on the verge of doing a new release, and if you build a new release build from git head it will be significantly faster.

3) The default --block-size  is way too small for files that large.  I recommend choosing a block size that is about sqrt(file-size).  For a filesystem image you probably also want something that is a multiple of the filesystem block size.  For that filesize I'd recomment 512K, or --block-size=524288. You can go smaller than that for smaller delta's, but it will make calculating them slower.

4) The default --input-size and --output-size (for versions before 2.0.1) is too small.  They should be at least as big as your --block-size. For --block-size=524288 I'd recommend --input-size=524288 --output-size=2097162.

**Comment by eomanis** [comment]
@dbaarda Thanks for the summary.

1. The images are not compressed, it takes long enough to pull them the way they are :-) Also I am using full-disk encryption and the disk was pseudo-randomed completely on OS setup, so applying encryption would only serve to electrically heat the room.
2. Good point, I'll look into that. I have however noticed that although `rdiff -V` and the Arch Linux package manager both report librsync 1.0.0, the `librsync` package actually installs a librsync.so.2.0.0:
```
[builduser@mysystem ~]$ IFS=$'\n' ls -l $(find $(pacman -Qql librsync) -maxdepth 0 -not -type d)
-rwxr-xr-x 1 root root 14656 17. Jan 2016  /usr/bin/rdiff
-rw-r--r-- 1 root root  1395 17. Jan 2016  /usr/include/librsync-config.h
-rw-r--r-- 1 root root 14155 17. Jan 2016  /usr/include/librsync.h
lrwxrwxrwx 1 root root    17 17. Jan 2016  /usr/lib/librsync.so -> librsync.so.2.0.0
lrwxrwxrwx 1 root root    17 17. Jan 2016  /usr/lib/librsync.so.2 -> librsync.so.2.0.0
-rwxr-xr-x 1 root root 64272 17. Jan 2016  /usr/lib/librsync.so.2.0.0
-rw-r--r-- 1 root root  1168 17. Jan 2016  /usr/share/man/man1/rdiff.1.gz
-rw-r--r-- 1 root root  1438 17. Jan 2016  /usr/share/man/man3/librsync.3.gz
```
When I build the package myself it looks the same.
The distribution package was built in Jan 2016.

As for your points 3 and 4, I'll try to use larger blocks, and I may also try to build and install a more recent version. And possibly badger the package maintainer to package v2.0.0.

**Comment by dbaarda** [comment]
If the images have full disc encryption, you might also find that you can't efficiently delta between them. Encryption generally has the same effect on data as compression, smearing small delta's widely across the data. However, I suspect that disk blocks are encrypted independently (because otherwise writing a single block would require re-writing most of the disk), so you will probably be OK.

The library version between v1.0.0 and v2.0.0 was a bit of a mess. The v1.0.0 release included a librsync.so.2.0.0 (semantic library version different to source version), v1.0.1 switched to CMake and ended up with a librsync.so.1.0.1, and v2.0.0 fixed things so that the source version == the library soversion and had a librsync.so.2.0.0 again. The next version will be v2.0.1 with a librsync.so.2.0.1. So I believe the version you are running really is software release version v1.0.0, which is very old.

When building your own rdiff binary, make sure to run ccmake . and change the build type to "Release", so that you build a nice fast binary without debugging in it.

**Comment by eomanis** [comment]
I have managed to build and package v2.0.0 by modifying the original PKGBUILD for v1.0.0.
The build appears to be lacking the manual pages however.
If I am to bug the maintainer of the Arch Linux `librsync` package to upgrade to v2.0.0 I should at least have the courtesy to provide a working PKGBUILD.

For the record, PKGBUILDs are Bash scripts that are sourced by the Arch Build System (abs) to build and package software.

From the original PKGBUILD for v1.0.0:
```
(...)
pkgname=librsync
pkgver=1.0.0
source=($pkgname-$pkgver.tar.gz::https://github.com/$pkgname/$pkgname/archive/v$pkgver.tar.gz)
(...)

build() {
  cd "$srcdir/$pkgname-$pkgver"

  ./autogen.sh
  ./configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --enable-shared
  make
}

check() {
  cd "$srcdir/$pkgname-$pkgver"
  make -k check
}

package() {
  cd "$srcdir/$pkgname-$pkgver"
  make DESTDIR="$pkgdir" install
}
```
From the PKGBUILD that builds v2.0.0:
```
(...)
pkgname=librsync
pkgver=2.0.0
source=($pkgname-$pkgver.tar.gz::https://github.com/$pkgname/$pkgname/archive/v$pkgver.tar.gz)
(...)

build() {
  cd "$srcdir/$pkgname-$pkgver"
  cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DPOPT_INCLUDE_DIRS=/usr/include \
    -DSITE_NAME=none \
    .
    # TODO --mandir=/usr/share/man
    # TODO --enable-shared
  make
}

check() {
  cd "$srcdir/$pkgname-$pkgver"
  make test
}

package() {
  cd "$srcdir/$pkgname-$pkgver"
  make DESTDIR="$pkgdir" install
}
```
As you can see, I have not yet managed to "port" the ./configure arguments `--mandir=/usr/share/man` and `--enable-shared` to `cmake` (I am not familiar with either make or cmake).
`ccmake` did not show me a variable for the manual pages directory either.
Doxygen is available.
How do I get `make` to create and install the manual pages?

Here the output of a clean v2.0.0 build so far:
```
[builduser@mysystem community-x86_64]$ makepkg -f
==> Making package: librsync 1:2.0.0-1 (Mo 9. Okt 20:30:51 CEST 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found librsync-2.0.0.tar.gz
==> Validating source files with sha256sums...
    librsync-2.0.0.tar.gz ... Passed
==> Extracting sources...
  -> Extracting librsync-2.0.0.tar.gz with bsdtar
==> Starting build()...
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for include file alloca.h
-- Looking for include file alloca.h - found
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file bzlib.h
-- Looking for include file bzlib.h - found
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file malloc.h
-- Looking for include file malloc.h - found
-- Looking for include file mcheck.h
-- Looking for include file mcheck.h - found
-- Looking for include file sys/file.h
-- Looking for include file sys/file.h - found
-- Looking for include file zlib.h
-- Looking for include file zlib.h - found
-- Looking for alloca
-- Looking for alloca - not found
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for memmove
-- Looking for memmove - found
-- Looking for memset
-- Looking for memset - found
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for strchr
-- Looking for strchr - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for vsnprintf
-- Looking for vsnprintf - found
-- Looking for _snprintf
-- Looking for _snprintf - not found
-- Looking for _vsnprintf
-- Looking for _vsnprintf - not found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Check size of off_t
-- Check size of off_t - done
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Check size of unsigned short
-- Check size of unsigned short - done
-- RS_LONG_T = long long
-- PROJECT_NAME  = librsync
-- SITE_NAME  = none
-- Found POPT: /usr/lib/libpopt.so  
-- Found components for POPT
-- POPT_ROOT_DIR  = /usr
-- POPT_INCLUDE_DIRS  = /usr/include
-- POPT_LIBRARIES = /usr/lib/libpopt.so
-- Found BZip2: /usr/lib/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found components for BZIP2
-- BZIP2_INCLUDE_DIR  = /usr/include
-- BZIP_LIBRARIES = /usr/lib/libbz2.so
-- Found Perl: /usr/bin/perl (found version "5.26.1") 
-- PERL_EXECUTABLE  = /usr/bin/perl
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Found components for ZLIB
-- BZIP2_INCLUDE_DIR  = /usr/include
-- BZIP_LIBRARIES = /usr/lib/libz.so
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen missing components:  dot
-- Configuring done
-- Generating done
-- Build files have been written to: /home/builduser/abs/librsync/repos/community-x86_64/src/librsync-2.0.0
Scanning dependencies of target isprefix_test
Scanning dependencies of target rsync
[  5%] Building C object CMakeFiles/isprefix_test.dir/tests/isprefix_test.c.o
[  5%] Building C object CMakeFiles/isprefix_test.dir/src/isprefix.c.o
[  8%] Building C object CMakeFiles/rsync.dir/src/base64.c.o
[ 11%] Building C object CMakeFiles/rsync.dir/src/prototab.c.o
[ 14%] Building C object CMakeFiles/rsync.dir/src/buf.c.o
[ 17%] Linking C executable isprefix_test
[ 20%] Building C object CMakeFiles/rsync.dir/src/checksum.c.o
[ 22%] Building C object CMakeFiles/rsync.dir/src/command.c.o
[ 22%] Built target isprefix_test
[ 25%] Building C object CMakeFiles/rsync.dir/src/delta.c.o
[ 28%] Building C object CMakeFiles/rsync.dir/src/emit.c.o
[ 31%] Building C object CMakeFiles/rsync.dir/src/fileutil.c.o
[ 34%] Building C object CMakeFiles/rsync.dir/src/hex.c.o
[ 37%] Building C object CMakeFiles/rsync.dir/src/job.c.o
[ 40%] Building C object CMakeFiles/rsync.dir/src/mdfour.c.o
[ 42%] Building C object CMakeFiles/rsync.dir/src/mksum.c.o
[ 45%] Building C object CMakeFiles/rsync.dir/src/msg.c.o
[ 48%] Building C object CMakeFiles/rsync.dir/src/netint.c.o
[ 51%] Building C object CMakeFiles/rsync.dir/src/patch.c.o
[ 54%] Building C object CMakeFiles/rsync.dir/src/readsums.c.o
[ 57%] Building C object CMakeFiles/rsync.dir/src/rollsum.c.o
[ 62%] Building C object CMakeFiles/rsync.dir/src/scoop.c.o
[ 62%] Building C object CMakeFiles/rsync.dir/src/search.c.o
[ 65%] Building C object CMakeFiles/rsync.dir/src/stats.c.o
[ 68%] Building C object CMakeFiles/rsync.dir/src/stream.c.o
[ 71%] Building C object CMakeFiles/rsync.dir/src/sumset.c.o
[ 74%] Building C object CMakeFiles/rsync.dir/src/trace.c.o
[ 77%] Building C object CMakeFiles/rsync.dir/src/tube.c.o
[ 80%] Building C object CMakeFiles/rsync.dir/src/util.c.o
[ 82%] Building C object CMakeFiles/rsync.dir/src/version.c.o
[ 85%] Building C object CMakeFiles/rsync.dir/src/whole.c.o
[ 88%] Building C object CMakeFiles/rsync.dir/src/blake2b-ref.c.o
[ 91%] Linking C shared library librsync.so
[ 91%] Built target rsync
Scanning dependencies of target rdiff
[ 97%] Building C object CMakeFiles/rdiff.dir/src/isprefix.c.o
[ 97%] Building C object CMakeFiles/rdiff.dir/src/rdiff.c.o
[100%] Linking C executable rdiff
[100%] Built target rdiff
==> Starting check()...
Running tests...
Test project /home/builduser/abs/librsync/repos/community-x86_64/src/librsync-2.0.0
    Start 1: isprefix_test
1/8 Test #1: isprefix_test ....................   Passed    0.00 sec
    Start 2: Help
2/8 Test #2: Help .............................   Passed    0.01 sec
    Start 3: Mutate
3/8 Test #3: Mutate ...........................   Passed    1.75 sec
    Start 4: Signature
4/8 Test #4: Signature ........................   Passed    0.13 sec
    Start 5: Sources
5/8 Test #5: Sources ..........................   Passed    0.50 sec
    Start 6: Triple
6/8 Test #6: Triple ...........................   Passed    0.01 sec
    Start 7: Delta
7/8 Test #7: Delta ............................   Passed    0.08 sec
    Start 8: Changes
8/8 Test #8: Changes ..........................   Passed    1.16 sec

100% tests passed, 0 tests failed out of 8

Total Test time (real) =   3.66 sec
==> Entering fakeroot environment...
==> Starting package()...
[  8%] Built target isprefix_test
[ 91%] Built target rsync
[100%] Built target rdiff
Install the project...
-- Install configuration: "Release"
-- Installing: /home/builduser/abs/librsync/repos/community-x86_64/pkg/librsync/usr/lib/librsync.so.2.0.0
-- Installing: /home/builduser/abs/librsync/repos/community-x86_64/pkg/librsync/usr/lib/librsync.so.2
-- Installing: /home/builduser/abs/librsync/repos/community-x86_64/pkg/librsync/usr/lib/librsync.so
-- Installing: /home/builduser/abs/librsync/repos/community-x86_64/pkg/librsync/usr/bin/rdiff
-- Set runtime path of "/home/builduser/abs/librsync/repos/community-x86_64/pkg/librsync/usr/bin/rdiff" to ""
-- Installing: /home/builduser/abs/librsync/repos/community-x86_64/pkg/librsync/usr/include/librsync.h
-- Installing: /home/builduser/abs/librsync/repos/community-x86_64/pkg/librsync/usr/include/librsync-config.h
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issue...
==> Creating package "librsync"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: librsync 1:2.0.0-1 (Mo 9. Okt 20:31:01 CEST 2017)
```

**Comment by dbaarda** [comment]
I'm curious why you have targeted the released v2.0.0 vs the no-yet-released v2.0.1 you could get with a git clone of master?. Note v2.0.1 will be 5~10x faster than v2.0.0, and includes a bunch of fixes.

I'm not sure if you are suggesting we add a BUILDPKG to our git repo. I'm not sure we want to do that. We currently have debian and rpm package building stuff in the repo but in practice nobody updates them and they end up worse than useless. See #96 for discussions on removing them.

It looks to me like the CMake install setup in our CMakeLists.txt doesn't include installing the man pages. The man pages are doc/rdiff.1 and doc/librsync.3 and don't require Doxygen, they just need to be installed into the correct location. I know Doxygen can generate man pages for libraries from the code, but we are not using that.

If you figure out the right way to configure CMake to install the man pages, I'd welcome a pull request. We are in the process of trying to polish 2.0.1 up for an imminent release and something like that would be nice before we do the release.

**Comment by dbaarda** [comment]
Also, just using your existing v1.0.0 with the larger --block-size --input-size, and --output-size flags should be order 100x or more faster than you had before. Using v2.0.1 would be 5~10x faster again, but the biggest win would be from the larger block-size.

**Comment by dbaarda** [comment]
I'm glad you've worked it out. Using git is not so hard, but maybe I think that because I'm fairly familiar with it now. The main advantage of targeting v2.0.1 is it's also possible to fix our git sources before the release if that makes things easier.

To just quicky try it you can do;

$ cd <some parent dir>
$ git clone https://github.com/librsync/librsync.git
$ cd librsync
$ cmake -D CMAKE_BUILD_TYPE=Release -D ENABLE_TRACE=1 .
$ make check

Note you can also run the following to see and change cmake options;

$ ccmake .

I'd be curious to hear how the larger block size goes with v1.0.0 and if you notice much difference between v1.0.0 and v2.0.0. I'm pretty sure you'll notice a huge difference with v2.0.1 when you get around to trying it.

But I'm pretty sure we've addressed this bug so I"m going to close it, but feel free to add more feedback comments with info from any followup, or re-open if you think there are still some things that need to be addressed.

**Comment by dbaarda** [comment]
In case you didn't notice, I just released v2.0.1. I strongly suggest you focus on that release, as it is significantly better than any earlier release.

**Comment by eomanis** [comment]
@dbaarda Thank you very much, it builds without problems from the new .tar.gz.
My internet connection was broken during the last few days so I couldn't check. I'll give it a try, with appropriate block/buffer sizes.

**Comment by dbaarda** [comment]
You shouldn't need to set the buffer sizes with v2.0.1, as it now sets sensible defaults. However, you will still need to set the block size.

**Comment by eomanis** [comment]
I gave v2.0.1 a whirl with the large files and a block size of 1 MiB.
That was before your hint that now rdiff uses smarter buffer sizes, so I used 16 MiB for both input and output.

The baseline:
`signature` is very fast and causes only negligible CPU load, with an I/O-limited speed of 96.8 MB/s, and now yields a comfortably small signature file of 8.2 MB.

`delta` is way faster than before and now usable, but still CPU-limited with 30.0 MB/s. It appears to be single-threaded; if it were multi-threaded, assuming a roughly proportionate scaling to the available 4 cores my system could likely satisfy the I/O.

`patch` is like `signature` in terms of speed and CPU load.

@dbaarda , one question about the block size:
Is the `--block-size=N` option in any way effective for `delta` and `patch`?
From my understanding it just tells the block size over which the hash(es) are calculated when creating the signature, and those hashes are then stored in the signature file. Therefore for `delta` the block size is fixed, determined by whatever was used when creating the signature file, and the same goes for `patch` where the block size then comes from the delta file, right?

**Comment by dbaarda** [comment]
I'm glad to hear it's now much faster for you. You are correct that -`-block-size` (and `--sum-size`) are irrelevant for `patch` and `signature`, as they are only used for calculating the signature. Note block size is mostly irrelevant for `delta` because the patch's `copy` (copy match data) and `literal` (insert miss data) commands are all byte based... you can only figure out what size the block might have been from `copy` commands all being a multiple of the original block size.

For `signature`, you can make them even smaller by selecting a less paranoid `--sum-size`. The current default is a very paranoid 32 bytes, which is designed to thwart attacks using crafted data to try and generate blocksum collisions. Realistically, you don't need anywhere near that large a blocksum. My recommended blocksum size is 

  sum_size = 2 + (2*ln2(old_fsize) - ln2(*block_len) + 7)/8

So for a 256GB file (2^38) with a 1MB block size (2^20), you use 2 + (2*38 - 20 + 7)/8 = 9 bytes. This should still give you at worst a 1 in 2^32 chance of a blocksum collision, with a signature that is nearly 1/3 the size. If you are a bit more paranoid, you can use sum_size = 14 to give you at least 1 in 2^72 chance of a blocksum collision with a signature 1/2 the size.

For `delta`, the way the algorithm works it's not at all easy to parallelize it, since it walks through the data a byte at a time looking for matches, and matches early in the file affect alignment for future matches in the file, so it's not possible to just divide the file up into pieces to run in parallel. At least, not without an impact on the delta size. I guess it could be done be done by just dividing the file into pieces for each thread and sacrifice potential block matches on the dividing boundaries... or some kind of ugly post-checking for boundary block matches separately.
