### ISSUE TITLE
key_t in tests/hashtable_test.c may conflict with sys/types.h 

### ISSUE THREAD

**Issue by wRAR** [librsync/librsync#134]
On kFreeBSD tests/hashtable_test.c fails to compile:

```
/«PKGBUILDDIR»/tests/hashtable_test.c:30:13: error: conflicting types for 'key_t'
 typedef int key_t;
             ^~~~~
In file included from /usr/include/stdlib.h:275:0,
                 from /«PKGBUILDDIR»/src/hashtable.h:24,
                 from /«PKGBUILDDIR»/tests/hashtable_test.c:27:
/usr/include/x86_64-kfreebsd-gnu/sys/types.h:122:17: note: previous declaration of 'key_t' was here
 typedef __key_t key_t;
                 ^~~~~
```

It may be a coincidence that the conflict doesn't happen on Linux as `<sys/types.h>` there may define this type too.

**Comment by dbaarda** [comment]
Ugh, I'm sorry about that. There doesn't seem to be that typedef on linux.

That is just the unittest example and could use any name. I'll try to fix it as part of a big name audit.

**Comment by wRAR** [comment]
> There doesn't seem to be that typedef on linux.

Either the file doesn't get included or the conditions are false. There *is* that typedef in `<sys/types.h>` on my Linux.
