### ISSUE TITLE
Github generated tarballs change randomly

### ISSUE THREAD

**Issue by bket** [librsync/librsync#146]
As the title states, github generated tarballs can change at any point. This creates issues for packaging on systems like [OpenBSD](https://marc.info/?l=openbsd-ports&m=151973450514279&w=2) ports. Would it be possible to get official tarballs created / attached to releases?

**Comment by dbaarda** [comment]
What!?!? This sounds nasty. Is there any bug/discussion about this I can read up on?

Would downloading and then uploading the built tarball be enough to "freeze" it?

**Comment by bket** [comment]
There are plenty of sources that had a discussion on this 'feature', for example:

- https://github.com/easybuilders/easybuild-easyconfigs/issues/5151
- https://github.com/libgit2/libgit2/issues/4343#issuecomment-328631745
- https://github.com/Homebrew/homebrew-core/issues/18044
- https://marc.info/?l=openbsd-ports&m=151973450514279&w=2

**Comment by dbaarda** [comment]
It looks like if we download the tar.gz after creating a release, then edit the release and upload it, you end up with another downloadable target that should be stable. I just did this for the v2.0.2 release.

I'm going to update the release procedure docs to include doing this, and then declare it fixed.
