### ISSUE TITLE
Is it possible to merge multiple patches?

### ISSUE THREAD

**Issue by gmenegatti** [librsync/librsync#148]
Hi there,

Considering that I generate a diff/patch for a specific file every time that it is modified and that I store all these diffs/patches individually and sequentially, would it be possible to merge all patches into a single (final) patch that covers all the changes on the file and only apply this final patch?

Is it possible to do that using librsync? If not, is there any conceptual limitation/challenge that would make it impossible to implement it?

If my interpretation is not wrong, the Xdelta lib has support for what I'm asking above. Just to make it clear, the intention here is not to compare the two, but just to clarify what I'm trying to achieve with librsync.

> The new merge command allows you to combine a sequence of deltas, to produce a single output that represents the net effect of the sequence. The command is reasonably efficient because it computes the result directly, without constructing any intermediate copies (and without access to the first-of-chain source).

Source: https://github.com/jmacd/xdelta/issues/36

Thanks in advance.
Gabriel

**Comment by dbaarda** [comment]
Currently librsync doesn't directly support merging patches.

The easiest way to do this with librsync currently is to sequentially apply the patches, and then compute a new delta. This is something you could do if you wanted to "discard intermediate patches", as the result would probably be a little smaller than the sum of the patches you "merged", and would definitely be faster to apply later than sequentially applying them.

In theory it should be possible to create a new command that merges patches, but it would not be trivial to implement, and there are probably higher priority things to work on.

BTW, one of the things I've started thinking about is supporting VCDIFF format deltas (which is a standard xdelta uses). If librsync supported these deltas, then probably xdelta could be used to merge them. Note librsync's main benefit over xdelta is remote-delta calculation from signatures. There is no reason why the delta file format needs to be different.

I'm going to consider this answer to have answered your question and close this. If you really want "merge patch" or "VCDIFF format deltas", please file another bug requesting them.
