### ISSUE TITLE
Removing an applied patch without the original file

### ISSUE THREAD

**Issue by gmenegatti** [librsync/librsync#152]
Hello,

Please, is there a way to "remove" a diff patch applied to a file, but without having the original file (before the patch application)?

Thanks in advance.

**Comment by dbaarda** [comment]
No. 

The patch could have included deletes and overwrites. Without the original file there is no way to know what the deleted or overwritten data was.

There is a slim chance that the patch didn't delete or overwrite anything, in which case it would be possible, but it would be a bit tricky to do.
