### ISSUE TITLE
rdiff (librsync 2.2.0) hangs on large files

### ISSUE THREAD

**Issue by hmalzahn** [librsync/librsync#176]
After the latest update, rdiff delta hangs if used on files larger than about 5G. Here's how to reproduce the problem:

 dd if=/dev/urandom of=testfile bs=1M count=1 seek=5500
 rdiff signature testfile testfile.sig
 rdiff delta testfile.sig - - <testfile >testfile.delta

Which hangs after writing 11264000 bytes into testfile.delta

**Comment by dbaarda** [comment]
Note that your cmdline "rdiff delta testfile.sig - - testfile.delta" gives an error "rdiff: Too many arguments.". Did you'r cut-n-paste drop some `<` or `>` characters thinking they were tags?... ha, yes, editing your comment shows me what you actually meant;

`rdiff delta testfile.sig - - <testfile >testfile.delta`

This does appear to be reproducible for me, and I'm investigating now. Note that this might be peculiar to sparse files and/or long runs of zero blocks, but it definitely shouldn't be happening.

**Comment by hmalzahn** [comment]
Yep, looks like the cut+paste didn't quite work, you've got the right command line.

I'm using rdiff for some backup jobs, and the problem occured with large backup files, so it has nothing to do with the content of the data. I was simply looking for a way to reproduce the error as easily as possible, hence the dd'd sparse file.

**Comment by dbaarda** [comment]
Found it;

https://github.com/librsync/librsync/commit/bcbb819edb89bb2c7f9bd7cfd4f6713aeead6940

What does this return;
```C
rs_long_t func() {
  rs_long_t val = 0x100000000;
  return val >> 64;
}
```
0 right? Surprise, it returns 0x100000000! At least it does with gcc.

It seems if you shift right by a value equal or greater than the number of bits in the value, it does nothing and just returns the value.

This means the rs_int_len() never terminates for int's that need more than 8 bytes.

**Comment by dbaarda** [comment]
I have a fix that I'll merge as soon as checks pass.

This is serious enough to warrant an immediate 2.2.1 release.

**Comment by dbaarda** [comment]
Fo the record, the C99 standard says shifting by the number of bits or more is undefined behavior..
