### ISSUE TITLE
cmake and pkg-config related build failure on FreeBSD

### ISSUE THREAD

**Issue by mandree** [librsync/librsync#198]
Greetings,

we are seeing build failures on FreeBSD if and only if pkg-config is available while cmake is being run. Our bug report is at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245514

I couldn't find terribly much in the history of https://github.com/librsync/librsync/commits/master/cmake/FindPOPT.cmake but at any rate, the `-L/usr/local/lib` argument does not show up in the linker command line if pkg-config is found.  This is our pkg-config output, which looks sane to me:

```
$ pkg-config --cflags popt
-I/usr/local/include 
$ pkg-config --libs popt
-L/usr/local/lib -lpopt
```

If pkg-config is found, then configure prints `--- POPT_LIBRARIES = popt` and the workaround is forcing down `LDFLAGS=-L/usr/local/lib` from our build rig, if pkg-config is NOT found, then FindPOPT will guess the library path directly as `--- POPT_LIBRARIES = /usr/local/lib/libpopt.so`.

```
[69/69] : && /usr/local/libexec/ccache/cc -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -Wall -std=c99 -pedantic -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -fstack-protector-strong CMakeFiles/rdiff.dir/src/rdiff.c.o CMakeFiles/rdiff.dir/src/isprefix.c.o  -o rdiff  -Wl,-rpath,/usr/ports.svn/net/librsync/work/.build:  librsync.so.2.3.0  -lpopt && :
FAILED: rdiff 
: && /usr/local/libexec/ccache/cc -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing -Wall -std=c99 -pedantic -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -fstack-protector-strong CMakeFiles/rdiff.dir/src/rdiff.c.o CMakeFiles/rdiff.dir/src/isprefix.c.o  -o rdiff  -Wl,-rpath,/usr/ports.svn/net/librsync/work/.build:  librsync.so.2.3.0  -lpopt && :
ld: error: unable to find library -lpopt
cc: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by dbaarda** [comment]
I'm on the verge of doing a v2.3.1 release so I'm glad you reported this. I'd like to fix this and #199 before I make that release.

At first glance this smells like a bug in CMake PkgConfig on FreeBSD. In general I'd rather avoid adding workarounds for every bug in every platform. However, for important platforms and small workarounds I guess it's OK.

Support for PkgConfig was added in #186 . If there's some way that you can see that this was done incorrectly and/or how to easily fix it I'd be delighted to accept pull requests. I don't have easy access to a FreeBSD platform to try/test fixes. I'll have a look at it and see if I can see anything obviously wrong though.

**Comment by mandree** [comment]
The pkg-config stuff in cmake only parses -l options into LIBRARIES, so it's missing the -L and possibly other flags, and the main CMakeLists.txt file does not look at LDFLAGS or LDFLAGS_OTHER where the other options from pkg-config output end up.

So the quick and dirty fix is changing this line in CMakeLists.txt:
`target_link_libraries(rdiff rsync ${POPT_LIBRARIES})`
to:
`target_link_libraries(rdiff rsync ${POPT_LDFLAGS} ${POPT_LDFLAGS_OTHER} ${POPT_LIBRARIES})`

I am not sure if that regresses elsewhere with semicolons in the <>_LDFLAGS<> variables or whatnot. I take it that such a simple change does not warrant a pull request.

_(It would seem that the pkg-config integration in cmake is still wanting after so many years.)_

**Comment by dbaarda** [comment]
I spent way too long fiddling with and tweaking cmake and finally put together something that should fix this properly once and for all in #200. I've also fixed #199 in that pull request because it's a 2 char change.

I'm going to merge this as soon as the tests pass, and then I'll start doing a v2.3.1 release.

**Comment by mandree** [comment]
Donovan, you haven't asked me if the tests work on FreeBSD but it appears they do. ;-) Thanks for the prompt fixes.

**Comment by dbaarda** [comment]
@mandree : Apologies, you are correct; I should have asked for confirmation that the fixes worked. Github auto-closed the bug when I merged the pull request with "Fixes ..." in the subject. I was pretty confident it would work (I spent waaay too long fiddling with it, reading docs, and finding corner cases etc), and my last comment on this bug was kind of a poorly implied question hoping you would give updates on how it works. 

Thank you very much for confirming that they do, and thank you also for the initial bug reports and all the help figuring out the fixes. I'll try to get the new v2.3.1 release out today.

**Comment by mandree** [comment]
Nevermind. Having read various comments on the commit history of FindPOPT.cmake and its contents, I wish that cmake would make it easier to integrate with pkg-config, rather than take the know-it-all or NIH approach... 

I'll ping my fellow port/package maintainer who oversees the FreeBSD librsync port that 2.3.1 is coming up.

Thanks again for the prompt fixes!

**Comment by dbaarda** [comment]
@mandree FYI v2.3.1 is released... It also includes some performance improvements.
