### ISSUE TITLE
Handling of breaking changes to rdiff

### ISSUE THREAD

**Issue by ericzolf** [librsync/librsync#204]
We're using rdiff to test that we're using the library properly, but especially since 2.0 almost each version introduced breaking changes, which is fine but makes my life miserable.

I've created a specific request for the last change in https://github.com/librsync/librsync/pull/109#issuecomment-632515736_ but I'd like to come to a more genetic agreement on how to handle this in the future.

Here my ideas in increasing order of preference for me but probably of effort for you:

1. Document explicitly in the release notes which parameter value keeps the compatibility
2. Document in the help text the same thing
3. Add a parameter `--compatible` to keep the previous behavior
4. Introduce new parameters/features in a backward compatible way

What do you think? Is any of this feasible?

**Comment by dbaarda** [comment]
I've responded on the original issue that prompted this here;

https://github.com/rdiff-backup/rdiff-backup/issues/304

In summary, I thought I was documenting any changes in releases that would impact compatibility but;

1. I underestimated how confusing my descriptions of the changes might be to people less familiar with the internals than me.
2. I didn't realize that some people's definition of "compatibility" might mean byte-identical output, not just fully-backwards-compatible output.

I will try to do better in my change descriptions in the future, and I'll edit the existing release descriptions to try and make things clearer.

I'm not sure if adding `--compatible` is a great idea... compatibility is pretty relative, and attempting to define a flag to encapsulate this will likely complicate and confuse things more than help.

I'll close this after I've updated the existing release descriptions to explain things better.

**Comment by dbaarda** [comment]
I've now edited the release descriptions for v2.2.0 and v2.3.0 where changes affecting the signatures were added.

Note that these changes do align with bumps to the minor version where we added additional functionality (new rollsum in v2.2.0 and new default block/sum sizes in v2.3.0).

I hope this is satisfactory for now, and I'll followup in the rdiff-backup bug to try and make transitions easier for you on that side...

I'm going to close this now, but feel free to re-open it if you think there is more that could/should be done.

**Comment by ericzolf** [comment]
Thanks very much, I'm fully happy to have this documented in the release notes.
