### ISSUE TITLE
Simple way to compare signatures in memory?

### ISSUE THREAD

**Issue by gatuno** [librsync/librsync#205]
Hi

I'm writing a custom backup program. And want to use librsync and rdiff. I managed to get the signature of a remote file by network. And have a local signature of the current local version of file, there is a function to compare to signatures and make sure is the same file?

Thanks.

**Comment by dbaarda** [comment]
Provided the signatures were created using the same rdiff args (--block-size --sum-size --hash --rollsum), then you can just compare them using diff; if the sigs are different, the files are different.

But if all you want to do is check if the files are different, then there are much more efficient ways to do it. You could use md5sum or shasum to get the wholefile hash and compare those.

The main advantage of librsync/rdiff signatures is it can calculate delta's against those signatures. If you want to know HOW different the file is, you could get librsync/rdiff to generate a delta; the smaller the delta, the smaller the amount of difference.

Does that answer your question?

**Comment by gatuno** [comment]
First of all, I'm impressed. I didn't expect an answer saying that 'other hashes' are more efficient.

I managed to write a patch today, which I attached to this issue.

In either case, I 'feel', like a user of this library, that there are some 'utility' functions missing. Like, one that allows to save a signature already loaded in a `rs_signature_t` to disk. I know what you would say, if you received the signature from network, you should have already the same bytes. It could be useful.

```
diff --git a/src/librsync.h b/src/librsync.h
index e39e5ae..787b4d0 100644
--- a/src/librsync.h
+++ b/src/librsync.h
@@ -290,6 +290,9 @@ LIBRSYNC_EXPORT void rs_free_sumset(rs_signature_t *);
 /** Dump signatures to the log. */
 LIBRSYNC_EXPORT void rs_sumset_dump(rs_signature_t const *);
 
+/** Compare two signtaures and returns 0 if they are the same. */
+LIBRSYNC_EXPORT int rs_sumset_cmp(rs_signature_t const *sig_a, rs_signature_t const *sig_b);
+
 /** Description of input and output buffers.
  *
  * On each call to ::rs_job_iter(), the caller can make available
diff --git a/src/sumset.c b/src/sumset.c
index 276e818..80b01a5 100644
--- a/src/sumset.c
+++ b/src/sumset.c
@@ -319,3 +319,37 @@ void rs_sumset_dump(rs_signature_t const *sums)
                strong_hex);
     }
 }
+
+int rs_sumset_cmp(rs_signature_t const *sig_a, rs_signature_t const *sig_b)
+{
+    int i, ret;
+    rs_block_sig_t *a, *b;
+    
+    if (sig_a->magic != sig_b->magic) {
+        return sig_a->magic - sig_b->magic;
+    }
+    
+    if (sig_a->block_len != sig_b->block_len) {
+        return sig_a->block_len - sig_b->block_len;
+    }
+    
+    if (sig_a->strong_sum_len != sig_b->strong_sum_len) {
+        return sig_a->strong_sum_len - sig_b->strong_sum_len;
+    }
+    
+    if (sig_a->count != sig_b->count) {
+        return sig_a->count - sig_b->count;
+    }
+    
+    for (i = 0; i < sig_a->count; i++) {
+        a = rs_block_sig_ptr(sig_a, i);
+        b = rs_block_sig_ptr(sig_b, i);
+        
+        ret = memcmp (a->strong_sum, b->strong_sum, sig_a->strong_sum_len);
+        
+        if (ret != 0) {
+            return ret;
+        }
+    }
+    return 0;
+}
```
