### ISSUE TITLE
LIBTOOL eval'd to nothing in autogen.sh message

### ISSUE THREAD

**Issue by MatthewHannigan** [librsync/librsync#21]
On [line 77](https://github.com/librsync/librsync/blob/master/autogen.sh#L77) of autogen.sh the var LIBTOOLIZE is eval'd whereas the message requires it to be not evaluated -- we're interested in the name not the value.

Obvious fix is to escape the $ - i.e. \$ but perhaps it would be better to change it to:
> echo "You can set the LIBTOOLIZE environment variable."

BTW, homebrew on Mac installs libtoolize as glibtoolize.

**Comment by sourcefrog** [comment]
Thanks!

> BTW, homebrew on Mac installs libtoolize as glibtoolize.

I saw that too when I tried to build there. I think autodetecting would be too complicated and maybe, per #39 , we'll stop using it anyhow.
