### ISSUE TITLE
Use buffer in memory instead of File

### ISSUE THREAD

**Issue by ashf** [librsync/librsync#210]
Ideally there would be a function: 
`rs_result rs_delta_file(rs_signature_t *, void * new_file, FILE * delta_file, rs_stats_t *)`

Note: I'd like to have the new_file in memory as opposed to a file on disk. This could be useful when compiling data together from a DB and creating a delta from this. If the data is very large, not having the extra IO overhead would be advantageous.

Is there a current workaround for this? I know there is fmemopen, but that doesn't work on Windows systems.

**Comment by dbaarda** [comment]
@ashf This can already be done using either the Streaming API;

https://librsync.github.io/api_streaming.html

Or perhaps easier for you using the Callback or "pull" API;

https://librsync.github.io/api_pull.html

Example callbacks for this that just read/write to files are here;

https://github.com/librsync/librsync/blob/master/src/buf.c

Note that you'll need to allocate the memory for the output, the size of which will be unknown until it completes. This suggests a series of doubling realloc's to grow the memory allocated as you go (and as I understand it, reallocs in windows can be expensive).

If you need any more help, feel free to reopen this with more questions. For now I'm going to consider it closed with this answer.
