### ISSUE TITLE
Generate signature from empty basis

### ISSUE THREAD

**Issue by ashf** [librsync/librsync#219]
The only way I can figure out how to create a signature from an empty basis, is to have an empty file on disk and use the `rs_file_open `+ `rs_sig_file` methods. Ideally, using the streaming API I could achieve the same, but I couldn't figure out how through experimentation and existing documentation. Any insight would be appreciated. Thanks!

**Comment by sourcefrog** [comment]
You could do it through the API without making a file, by providing your own callback methods, but there's no single method.

**Comment by dbaarda** [comment]
Note you can probably use `/dev/null` as the empty input file, so you don't need to create one yourself.

Do you actually need to create a signature file, or do you want just have one "loaded" and ready to create a delta with? Note the signature files don't include any distinguishing name/metadata/etc of the original file, so once you have generated one empty signature file, you can use that as the basis for any file delta.

If you just need an empty signature loaded and ready to delta against, you can do it like this;

```c
#include "librsync.h"
 
  char data[256];
  rs_buffers_t buf;
  rs_job_t *job;
  rs_signature_t *sig;
  rs_result res;

  # setup buf with empty input and space for signature output.
  buf.next_in = NUL;
  buf.avail_in = 0;
  buf.eof_in = 1;
  buf.next_out = data;
  buf.avail_out = sizeof(data);
 # Setup, run, and free the signature generate job.
  job = rs_sig_begin(0,0,0);
  while ((res = rs_job_iter(job, &buf)) == RS_RUNNING);
  assert(res == RS_DONE);
  rs_job_free(job);
  # data now contains the signature file.
  # setup buf with signature for input.
  buf.next_in = data;
  buf.avail_in = buf.next_out - data;
  buf.eof_in = 1;
  buf.next_out = NUL;
  buf.avail_out = 0;
  # Setup, run, and free signature load job.
  job = rs_loadsig_begin(&sig);
  while ((res = rs_job_iter(job, &buf)) == RS_RUNNING);
  assert(res == RS_DONE);
  rs_job_free(job);
  # sig now contains the loaded signature ready to delta against.
  rs_build_hash_table(sig);
```
