### ISSUE TITLE
Build failure because of search.c

### ISSUE THREAD

**Issue by posophe** [librsync/librsync#23]
32s] search.c: In function 'rs_build_hash_table':
[   32s] search.c:131:1: warning: declaration of 'rs_search_for_block' shadows a global declaration [-Wshadow]
[   32s]  rs_search_for_block(rs_weak_sum_t weak_sum,
[   32s]  ^
[   32s] In file included from search.c:47:0:
[   32s] search.h:24:1: warning: shadowed declaration is here [-Wshadow]
[   32s]  rs_search_for_block(rs_weak_sum_t weak_sum,
[   32s]  ^
[   32s] search.c: In function 'rs_search_for_block':
[   32s] search.c:149:6: warning: declaration of 'i' shadows a previous local [-Wshadow]
[   32s]   int i = sig->targets[m].i;
[   32s]       ^
[   32s] search.c:80:9: warning: shadowed declaration is here [-Wshadow]
[   32s]      int i;
[   32s]          ^
[   32s] search.c:154:4: warning: implicit declaration of function 'rs_calc_strong_sum' [-Wimplicit-function-declaration]
[   32s]     rs_calc_strong_sum(inbuf, block_len, &strong_sum);
[   32s]     ^
[   32s] search.c: In function 'rs_build_hash_table':
[   32s] search.c:172:1: error: expected declaration or statement at end of input
[   32s]  }
[   32s]  ^
[   32s] search.c:172:1: error: expected declaration or statement at end of input
[   32s] search.c:172:1: warning: control reaches end of non-void function [-Wreturn-type]
[   32s]  }
[   32s]  ^

Not sure if it does have something to do with this issue but I have applied the patch from
PR#14

**Comment by posophe** [comment]
[UPDATE] after corrections, I got this:
./.libs/librsync.so: undefined reference to `rs_calc_strong_sum'

**Comment by sourcefrog** [comment]
`rs_calc_strong_sum` was removed in the most recent release. You have a dirty build or something.
