### ISSUE TITLE
Determine delta size before generation (streaming api)

### ISSUE THREAD

**Issue by ashf** [librsync/librsync#240]
I'd like to upload a delta to an external endpoint (azure blob storage via the Azure Blob Storage client library v12 for C++). 

In order to be efficient (I have some very large files) I am using the streaming api to generate the delta, and only generating as much as being requested by the uploading api on an as needed basis. 

The caveat is that the azure library needs to know the upload (delta) size before the upload (streaming api utilization) is started. Is there anyway we can determine the delta size before calculating it? I could do a "dry-run" but I'd really like to avoid doing that.

**Comment by sourcefrog** [comment]
Just to confirm, you would want to know the exact size in bytes of the delta file? No, there's no API for that, and calculating it would be about as much work as computing the delta, so you might as well just do that.

But, is it really true that Azure needs to know the size of the whole file in advance? I haven't used it but that seems quite limiting. From memory GCS and S3 have APIs where the client provides a series of chunks without needing to know the total in advance. Maybe there is a different API you could use on that side?

**Comment by ashf** [comment]
> Just to confirm, you would want to know the exact size in bytes of the delta file? No, there's no API for that, and calculating it would be about as much work as computing the delta, so you might as well just do that.
> 
> But, is it really true that Azure needs to know the size of the whole file in advance? I haven't used it but that seems quite limiting. From memory GCS and S3 have APIs where the client provides a series of chunks without needing to know the total in advance. Maybe there is a different API you could use on that side?

You're correct in interpretating what I want to achieve. And I figured the answer would be what you wrote. 

You're also correct in that Azure provides a way to chunk (block) upload, I'll utilize that method instead. But figured I'd ask if there was a way to avoid doing that from the librsync side.

Thanks for the quick response!
