### ISSUE TITLE
signature.test fails on big endian

### ISSUE THREAD

**Issue by wRAR** [librsync/librsync#25]
librsync 1.0.0 failed to build on Debian buildds for architectures mips, powerpc and s390x, because signature.test failed:

```
    ../rdiff --hash=md4 -I4096 signature ./signature.input/01.in /tmp/librsynctest_eR3ZJiKg/signature
    ../rdiff --hash=md4 -I1 signature ./signature.input/01.in /tmp/librsynctest_eR3ZJiKg/signature
    ../rdiff --hash=md4 -I2 signature ./signature.input/01.in /tmp/librsynctest_eR3ZJiKg/signature
    ../rdiff --hash=md4 -I3 signature ./signature.input/01.in /tmp/librsynctest_eR3ZJiKg/signature
    ../rdiff --hash=md4 -I7 signature ./signature.input/01.in /tmp/librsynctest_eR3ZJiKg/signature
    ../rdiff --hash=md4 -I15 signature ./signature.input/01.in /tmp/librsynctest_eR3ZJiKg/signature
    ../rdiff --hash=md4 -I100 signature ./signature.input/01.in /tmp/librsynctest_eR3ZJiKg/signature
    ../rdiff --hash=md4 -I10000 signature ./signature.input/01.in /tmp/librsynctest_eR3ZJiKg/signature
    ../rdiff --hash=md4 -I200000 signature ./signature.input/01.in /tmp/librsynctest_eR3ZJiKg/signature
    ../rdiff --hash=blake2 -I4096 signature ./signature.input/01.in /tmp/librsynctest_eR3ZJiKg/signature
./signature.input/blake2/01.sig /tmp/librsynctest_eR3ZJiKg/signature differ: char 17, line 1
: comparison failed from command:
```

I can provide additional info if you need.

**Comment by sourcefrog** [comment]
Can you have a look whether `WORDS_BIGENDIAN` and `NATIVE_LITTLE_ENDIAN` are getting set correctly?

**Comment by wRAR** [comment]
`WORDS_BIGENDIAN` is set, `NATIVE_LITTLE_ENDIAN` is unset (checked by a program including `config.h` and `blake2-impl.h`).

**Comment by sourcefrog** [comment]
I think the next step is to add a test that BLAKE2 produces the right hashes for specified input.

**Comment by sourcefrog** [comment]
This might have been fixed by the change to CMake - please re-test if you have a bigendian machine.

**Comment by wRAR** [comment]
Still fails in 01215e291a3d6d992bf4a2c3b22c47e37a02c0e3

**Comment by dbaarda** [comment]
This is either a bug in the CMake config for blake2, or its a bug in blake2 itself.

The blake2 we use is a copy of upstream taken some time ago, so if this is a blake2 bug, it may be fixed upstream already. I also note that Debian sid now has a libb2 package, so this is starting to be available as a library on some platforms, though I don't think it's widely enough available that we don't need to provide it ourselves. IMHO we should;

1) Check the endian related config settings needed by blake2 vs what we have in our config.h and CMakeLists.txt to make sure we are setting things right.

2) Get a newer copy from upstream to see if it's an upstream bug that's been fixed.

3) Change our cmake config to use the platform provided library if it exists.

**Comment by dbaarda** [comment]
I had a look and there is nothing endian related in our CMakeLists.txt. Our config.h.cmake includes a bunch of #ifdef tests that look to me like it would default to little-endian unless on apple with AC_APPLE_UNIVERSAL_BUILD and  __BIG_ENDIAN__ defined, which is not exactly robust. IMHO we should use [cmake's TestBigEndian](https://cmake.org/cmake/help/v3.5/module/TestBigEndian.html).

However, your tests seem to indicate that the existing limited endian check is correctly detecting your platform as big-endian. This suggests it must be a blake2 bug in the version we have a copy of.

**Comment by dbaarda** [comment]
I just created pull request #113 to update to the latest blake2 reference implementation. Can someone check/confirm if this fixes this problem?

**Comment by wRAR** [comment]
Seems to work on s390x.

**Comment by dbaarda** [comment]
For the record, pull request #114 adds support for using libb2 if it is found.
