### ISSUE TITLE
popt.h issue

### ISSUE THREAD

**Issue by htbase** [librsync/librsync#28]
When running make install, we get the following (we are running RHEL 7):

libtool: link: ranlib .libs/librsync.a
libtool: link: ( cd ".libs" && rm -f "librsync.la" && ln -s "../librsync.la" "librsync.la" )
gcc -DHAVE_CONFIG_H -I.     -Wall -Wshadow -Wundef -Wwrite-strings -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wpointer-arith -Wcast-qual -Wcast-align -g -O2 -MT rdiff.o -MD -MP -MF .deps/rdiff.Tpo -c -o rdiff.o rdiff.c
rdiff.c:54:18: fatal error: popt.h: No such file or directory
 #include <popt.h>
                  ^
compilation terminated.
make[1]: *** [rdiff.o] Error 1
make[1]: Leaving directory `/apps/librsync'
make: *** [install-recursive] Error 1

Any help would be much appreciated.

Thanks

**Comment by sourcefrog** [comment]
In head and in 1.0, popt is an external dependency - you need to install it
prior to building librsync.

However, I'll probably switch back to shipping it.

**Comment by sourcefrog** [comment]
popt is now shipped again in head.

**Comment by sourcefrog** [comment]
Actually, after the CMake switch, I don't think it makes sense to ship this. popt can be downloaded from http://rpm5.org/files/popt.
