### ISSUE TITLE
rs_job_iter needs to be called twice with eof=1

### ISSUE THREAD

**Issue by paulharris** [librsync/librsync#33]
This smells like a bug,
please see pull request with demonstration and comments.

**Comment by sourcefrog** [comment]
It does smell suspicious; thanks for the test case.

**Comment by dbaarda** [comment]
FTR I checked this against master and my recent pull request #119 and it's still there.

Arguably it's not a bug; the documented API says you need to keep calling rs_job_iter() until it returns RS_DONE (or an error). However, it is something that could be done better.

**Comment by sourcefrog** [comment]
thanks @dbaarda !
