### ISSUE TITLE
symlink comments unclear

### ISSUE THREAD

**Issue by paulharris** [librsync/librsync#37]
Hi,

I have trouble understanding the comments regarding "following symlinks"

```c
/* Follow all symlinks. */
__LA_DECL int archive_read_disk_set_symlink_logical(struct archive *);
/* Follow no symlinks. */
__LA_DECL int archive_read_disk_set_symlink_physical(struct archive *);
/* Follow symlink initially, then not. */
__LA_DECL int archive_read_disk_set_symlink_hybrid(struct archive *);
```

so,

LOGICAL -- follow all symlinks... what happens if there is a symlink loop?  I see there are tests related to this, does it treat the symlink as a symlink when its visited a second time?

PHYSICAL -- don't follow at all.  this is clear.

HYBRID -- ... this could use some expansion, although I'm not sure how best to describe it.
Does this mean: when iterating through the tree, only follow the first symlink in a path?  Thats terrible...
so if you have this structure (much like the test)
dir/file
dir/flink --> dir/file
dlink --> dir
(so the path dlink/flink points to --> dir/file)

So "LOGICAL" would treat dlink/file as a file, and dlink/flink as a __file__,
but "HYBRID" would treat dlink/file as a file, would treat dlink/flink as a __link__

ie only the first visited link (dlink) is followed/dereferenced.

**Comment by sourcefrog** [comment]
I'm pretty sure you didn't mean to file this against librsync.

**Comment by paulharris** [comment]
ah bugger
