### ISSUE TITLE
Ability to adjust headers that have already been written

### ISSUE THREAD

**Issue by paulharris** [librsync/librsync#38]
When writing a 7zip or zip file, there is no technical reason why we can't adjust the size of the entry *after* the data has been written.

This would be useful when writing generated data to an archive, and the final size of the data is not known until after it has been written.

Currently, the entire data would have to be buffered somewhere manually (in memory? on disk?), and once the final size is determined, only then can the data be pushed out to the archive.

This is problematic if the data is large.

**Comment by paulharris** [comment]
Also related to the zip/7zip "contents page" style archives, where writing to seekable output:

It would also be useful to be able to "cancel" an entry that had just been written.

eg, you write the data, and at the end discover that you actually don't want that data to stay in the output archive.   So you call eg "cancel entry", and it drops the entry out of the pending "contents page" (which I assume is written at the point the archive is closed), and rewinds the output file cursor back to where the entry's data started (ie truncating the archive to where it was before).

**Comment by sourcefrog** [comment]
I don't understand how this maps to librsync. Did you file against the wrong project? Or if not, can you be more explicit which parts of the librsync output you want to change?

**Comment by paulharris** [comment]
Sorry, this was for libarchive.
