### ISSUE TITLE
librsync.sourcefrog.net is 404 (Broken links in README.md)

### ISSUE THREAD

**Issue by edwaro** [librsync/librsync#43]
Links to the documentation are broken - 404 error.

**Comment by jrosiek** [comment]
+1 from me. It would be great to have working documentation...

**Comment by yb66** [comment]
and again

**Comment by sourcefrog** [comment]
should be fixed now, please take another look

**Comment by yb66** [comment]
@sourcefrog Yes, that fixed it. Thank you.
