### ISSUE TITLE
CMake transition changed the soname to librsync.so.1

### ISSUE THREAD

**Issue by foutrelis** [librsync/librsync#48]
Assuming the 1.0.1 release is binary compatible with 1.0.0, it needs to retain the "librsync.so.2" soname and under no circumstances use "librsync.so.1" (which was the soname back in the librsync 0.9.7 days).

I believe a new release must be made with the above correction; 1.0.1 cannot be packaged by Linux distros.

**Comment by Salamek** [comment]
In that case we need to change LIBRSYNC_MAJOR_VERSION to 2 (so version will be 2.0.1 or 2.0.0 ) cos this in CMakeLists.txt:

```
set_target_properties(rsync PROPERTIES VERSION ${LIBRSYNC_VERSION} SOVERSION ${LIBRSYNC_MAJOR_VERSION})
```

or just do
```
set_target_properties(rsync PROPERTIES VERSION ${LIBRSYNC_VERSION} SOVERSION 2)
```
but that is ugly... i think soversion should match major version... and cos there is librsync.so.2 "out there" binary compatible with 1.0.1... moving LIBRSYNC_MAJOR_VERSION to 2 is only ~clean solution

@sourcefrog ?

**Comment by sourcefrog** [comment]
Hi, thanks for flagging this regression.

In previous versions of librsync I followed the advice in the libtool manual to allow the software release version and the library version to be different. See https://github.com/librsync/librsync/blob/e2d3bdf88bb792b4c022afddb2e8462e519d0bc2/libversions.txt. 

However this is pretty crazy and confusing.

So I plan to fix this by just bumping the library version up to 2.0.0.
