### ISSUE TITLE
Travis build is failing to find popt dpkg

### ISSUE THREAD

**Issue by sourcefrog** [librsync/librsync#62]
https://travis-ci.org/sourcefrog/librsync/jobs/104554510#L115

I don't understand what changed to cause this.

**Comment by Salamek** [comment]
@sourcefrog hi, i just tested few things to help you solve this issue, i installed Ubuntu 12.04.5 LTS server in virtualbox and tested to install libpopt-dev... it failed as in travis.

#### Reason:

1. `apt-get update` fails to update package list (maybe check ~/apt-get-update.log mentioned in travis log)

2. `apt-get install libpopt-dev` is unable to find a package

#### Fix:

It looks like `us.archive.ubuntu.com` is broken for Ubuntu 12.04.5 LTS when i changed all sources in `/etc/apt/sources.list` to `cs.archive.ubuntu.com` (Czech Republic mirror) `apt-get update` went ok and `apt-get install libpopt-dev` was installed successfuly

But why it works in older travis VM's ??? IDK... maybe travis is using custom mirror and your build just hit exact time when it was broken ?

Maybe try to run that test again ? or try to add : 

```
before_install:
  - sudo apt-get update
```

**Comment by dbaarda** [comment]
Has this been fixed? It seems like travis build tests are passing fine.

**Comment by Salamek** [comment]
@dbaarda this should be solved (looks like temporary error of apt repository)

**Comment by dbaarda** [comment]
Based on that feedback, I'm declaring this fixed :-)
