### ISSUE TITLE
Building under windows

### ISSUE THREAD

**Issue by iNDicat0r** [librsync/librsync#66]
Trying to build a visual studio project using cmake and i get the following errors: 
...  Cannot open include file: 'alloca.h': No such file or directory ...
... Cannot open include file: 'dlfcn.h': No such file or .....
... Cannot open include file: 'strings.h': No such file or directory ...
...
 Cannot open include file: 'unistd.h': No such file or directory
Cannot open include file: 'bzlib.h': No such file or
Cannot open include file: 'mcheck.h': No such file 
Cannot open include file: 'sys/file.h': No such file ..
Cannot open include file: 'zlib.h': No such file

and at the end of the log file i get few of: fatal error LNK1120: 1 unresolved externals

Using windows 8.1 64bit, visual studio 2013.

Any idea what i should do?

**Comment by redserpent7** [comment]
Why is this closed without a solution or information?

**Comment by iNDicat0r** [comment]
Not with cmake...just got the sources and header files imported to my project and worked.
