### ISSUE TITLE
Why did rs_search_for_block() become using binary search?

### ISSUE THREAD

**Issue by lsylsy2** [librsync/librsync#78]
First, sorry for my poor English.
It seems in a6122f1be9c6229baebb9be2c9752dce28f37ded , rs_search_for_block() changed greatly, using a binary search algorithm to search for weak checksum matching, instead of a hash table.
Is there any discussion about it?
Append: open it as a issue because it may affect performance.

**Comment by MartinNowak** [comment]
It's using a binary search for the hash collision buckets, not for the global search.

**Comment by dbaarda** [comment]
The change to a binary search for hashtable collisions significantly improved librsync performance for large numbers of blocks (large files and/or small blocks), with no noticeable cost for small numbers of blocks. 

Prior to this change block match checking used to degenerate to O(N) for large N where N is the number of signature blocks. This change made it O(ln(N)). There are further refinements on the way to use a dynamically sized hashtable that should reduce it to O(1).

I don't think this is an issue that requires further action, so closing it now.
