### ISSUE TITLE
AppVeyor CI build fails to run tests

### ISSUE THREAD

**Issue by sourcefrog** [librsync/librsync#81]
See for example https://ci.appveyor.com/project/sourcefrog/librsync/build/1.0.20

**Comment by dbaarda** [comment]
I had a bit of a look at AppVeyor and it looks like there is a lot of setup work required to make this even begin to attempt builds. We don't have an appveyor.yml that would do this for us.

I think this counts as a portability problem (make tests run on windows), rather than a bug.

**Comment by dbaarda** [comment]
Note that Travis now has a windows build environment;

https://docs.travis-ci.com/user/reference/windows/

Perhaps we should just set up one of those? Would AppVeyor still be useful in addition to that?

**Comment by dbaarda** [comment]
We now have windows builds on travis, but travis is also being phased out in favor of github actions.

I seems that github actions is also replacing AppVeyor. See the following for another projects analysis and switch;

https://github.com/bovigo/vfsStream/issues/215

Given this I'm going to close this bug and create a new one to switch from Travis to Github Actions.
