### ISSUE TITLE
types.h not found

### ISSUE THREAD

**Issue by fengye87** [librsync/librsync#90]
As I've been having this `rs_search_for_block` crash problem ( #50 ) on 2.0.0 occasionally, I gave the master branch a shot. When I was compiling against the newly installed librsync, a compilation error pops out:

> /usr/local/include/librsync.h:40:19: fatal error: types.h: No such file or directory

I can see that `librsync.h` is including a `types.h`, but there's no sight of this file under `/usr/local/include`. Maybe there's one step missing in installation process to copy this file?

**Comment by sourcefrog** [comment]
We should probably just move those declarations inline into `librsync.h` after the inclusion of the config file.

**Comment by awesomebob** [comment]
For anyone else finding this issue from Google:
I was able to get around this by manually copying the src/types.h file to /usr/local/include/
