### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by geoffmacintosh** [librsync/librsync#99]
I can't seem to reach the http://librsync.sourcefrog.net/ site, and [Down for everyone or just me](http://downforeveryoneorjustme.com/http://librsync.sourcefrog.net/) agrees that it's down. I was just wondering if this is a known issue, and if the site will be back up at some point, or if there's a new main site to link to instead. Thanks in advance!

**Comment by Salamek** [comment]
Maybe we should move to https://pages.github.com/ ?

**Comment by geoffmacintosh** [comment]
That would seem ideal assuming the site would be simple to transfer. How was the original site generated?

**Comment by sourcefrog** [comment]
Possibly my fault, I'll have a look.

**Comment by eugenejen** [comment]
i think sourcefrog.net is a typo for http://librsync.sourceforge.net/

**Comment by sourcefrog** [comment]
The website is the Doxygen output from the source tree. It seems good if we point it to Github and then any maintainer can update it.

(We could possibly use readthedocs.org but that seems harder to do with Doxygen, and anyhow a separate issue from this.)

**Comment by sourcefrog** [comment]
https://github.com/librsync/librsync.github.io created.

**Comment by sourcefrog** [comment]
- [*] https://librsync.github.io/ exists with the current docs.
- [ ] Point librsync.net and librsync.sourcefrog.net to there

**Comment by geoffmacintosh** [comment]
Thanks for the fix! I appreciate it!
